name: CI Build

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  BUILD_VERSION: 1.1.0
  PACKAGE_RELEASE_NOTES: |
    All ShowMeTheXaml.Avalonia packages now have consistent versions
    ShowMeTheXaml.Avalonia.AvaloniaEdit: Rework and improvements

on:
  push:
  pull_request:
    branches:
      - '**:**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore dependencies
        run: dotnet restore
      - name: Append ci info to version
        if: github.ref != 'refs/heads/master' 
        run: |
          echo "BUILD_VERSION=$BUILD_VERSION-ci$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "PACKAGE_RELEASE_NOTES=This is the package for CI build $GITHUB_RUN_ID" >> $GITHUB_ENV
      - name: Build with dotnet
        run: dotnet build --no-restore --configuration Release /property:Version=$BUILD_VERSION /property:PackageReleaseNotes="$PACKAGE_RELEASE_NOTES"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nupkg
          path: '**.nupkg'